### ISSUE TITLE
Some assistance getting this up and running

### ISSUE THREAD

**Issue by Analect** [npcode/mattermost-docker#2]
@npcode 
Thanks for putting together this repo.

I was having difficulty in getting it up and running and wanted to check a few things with you.

1. For the SSL certificate stuff, I followed the first part of [this](https://github.com/mattermost/platform/blob/master/doc/install/Production-Ubuntu.md#set-up-nginx-with-ssl-recommended), in terms of generating a *.key and *.crt file ... and then renamed these as key-no-password.pem (putting it in /web/cert/private/) and cert.pem (putting in /web/cert/) respectively.
Is this the right approach in order to then work with your 'web' container [here](https://github.com/npcode/mattermost-docker/blob/master/web/Dockerfile)?

2. Running up postgres
For the 'volumes' references back on the host machine ... 
`- ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data`
Do these need any special permissioning?

The database is sluggish to start up, for some reason ... and gives a message that database wasn't properly shut down ... even when I'm creating a whole new container (rather than restarting an exising one).
```
LOG:  database system was interrupted; last known up at 2016-01-25 21:39:07 GMT
LOG:  incomplete startup packet
FATAL:  the database system is starting up
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/17208E8
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  database system was interrupted; last known up at 2016-01-25 21:55:41 GMT
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/1720950
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```
I explored (via docker-enter) the postgres container for other logs /var/log/postgresql, to see if that could give me some clues, but there were none, for some reason.  Have they been disabled in a config file somewhere?

When the db looked like it was eventually up ... I restarted both app and web containers, just to be safe.

`docker-compose restart app`
`docker-compose restart web`

The app gave me back the following logs
```
Configure database connection...SKIP
Wait until database is ready...
Starting platform
panic: Failed to open sql connection pq: the database system is starting up

goroutine 1 [running]:
github.com/mattermost/platform/store.setupConnection(0xc13e50, 0x6, 0xc8201c8150, 0x8, 0xc820018ba0, 0x57, 0xa, 0xa, 0x415e00, 0xc820018c58)
	/go/src/github.com/mattermost/platform/store/sql_store.go:180 +0x5be
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
	/go/src/github.com/mattermost/platform/store/sql_store.go:59 +0x11c
github.com/mattermost/platform/api.NewServer()
	/go/src/github.com/mattermost/platform/api/server.go:31 +0xb5
main.main()
	/go/src/github.com/mattermost/platform/mattermost.go:66 +0x688

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
code.google.com/p/log4go.NewFileLogWriter.func1(0xc8200707e0)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/filelog.go:84 +0xabc
created by code.google.com/p/log4go.NewFileLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/filelog.go:116 +0x380

goroutine 8 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82012bb80)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336
Configure database connection...SKIP
Wait until database is ready...
Starting platform
Configure database connection...SKIP
Wait until database is ready...
Starting platform
```
Does that look normal?

The web container logs just had:
`Starting Nginx`

Any input you might have to get this up and running would be greatly appreciated.
Thanks

**Comment by npcode** [comment]
Thank you for the reporting!

> For the SSL certificate stuff, I followed the first part of this, in terms of generating a *.key and *.crt file ... and then renamed these as key-no-password.pem (putting it in /web/cert/private/) and cert.pem (putting in /web/cert/) respectively.
Is this the right approach in order to then work with your 'web' container here?

It is correct if you didn't input passphrase while creating the key file.

> Running up postgres
For the 'volumes' references back on the host machine ... 
- ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
Do these need any special permissioning?

Yes but Docker will give the correct permission to the directory automatically.

I have some questions to understand your problem.

1. What happens when you try to acces your mattermost with your web browser? Connection refused or 502 gateway error?
2. Does `docker ps` show that db, app and web is up?
3. Are you sure that you accessed it via https? e.g. `https://host.domain`

**Comment by Analect** [comment]
@npcode 
I feel a bit foolish ... I was trying `http:\\localhost` instead of `https:\\` as you point out in 3 above.

Even though I have created the self-signed certificate, is it normal that I still get all these warnings about https://localhost ... when accessing via a web-browser?

![image](https://cloud.githubusercontent.com/assets/4063815/12572508/35cea124-c3e5-11e5-8205-ac0a1da1437c.png)

I did notice some slight problems in getting all three containers up and running simultaneously.  It seems if the database is not fast enough to offer a connection, then the other containers won't start. I see in the log output from the db container, that it refers to a previous instance not being closed properly ... this shows up even if I stop and remove earlier containers ... perhaps it has something to do with 'volumes' connection back to the host keeping remnants of the old database ... and perhaps that should be cleared as part of a clean-up process.
```
~/Development/Tools/misc/mattermost-docker$ docker-compose up -d
Creating mattermostdocker_db_1
Creating mattermostdocker_app_1
Creating mattermostdocker_web_1
ERROR: Cannot start container 2dffebe07b34f45c1c9baa9bbf5c9440f8600c15d20e9b50efac9c82942de83e: Cannot link to a non running container: /mattermostdocker_app_1 AS /mattermostdocker_web_1/platform
```
If I had another existing container running postgres (for another system), it's probably not advisable to have another exposing posrt 5432 too.  Therefore, it perhaps makes sense to extend the existing one.  Do you know if it's possible for me to run only the database creation step ... and somehow run this make_db.sh as a command within the docker-compose.yml? 

`ADD make_db.sh /docker-entrypoint-initdb.d/`

I presume it's OK to redirect port 80 in the app to a different port on the host, without impacting the app?

Thanks again for your quick response.

**Comment by npcode** [comment]
> I feel a bit foolish ... I was trying http:\\localhost instead of https:\\ as you point out in 3 above.

Sorry, I was too lazy to make the web server redirects 'http' to 'https' automatically. :)

> Even though I have created the self-signed certificate, is it normal that I still get all these warnings about https://localhost ... when accessing via a web-browser?

Yes, you will get the warning because you are using self-signed certificate which your browser doesn't trust. You can try [let's encrypt](https://letsencrypt.org/) to get a trusted certificate.

> If I had another existing container running postgres (for another system), it's probably not advisable to have another exposing posrt 5432 too. Therefore, it perhaps makes sense to extend the existing one. Do you know if it's possible for me to run only the database creation step ... and somehow run this make_db.sh as a command within the docker-compose.yml?

I think you don't need to extend the existing postgres. It's okay to have another existing container running postgress which uses port 5432, because each container has its own ip address. If you want to use the existing one, run `make_db.sh` in the container to create the database for mattermost and configure mattermost to use it.

> I presume it's OK to redirect port 80 in the app to a different port on the host, without impacting the app?

Do you want to redirect a certain port in your host to port 80 in the app? Yes, it's okay. You can do that by adding `ports` option in `app` section in `docker-compose.yml`.

**Comment by Analect** [comment]
Thanks again. I'll close this out for now.
